### ISSUE TITLE
rev-aggregate-metadata failed attempt to force reextraction on openneuro/ds0000001

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-revolution#113]
in your account on smaug, just source ``/home/mih/yoh-mih/datalad-revolution/venvs/dev3/bin/activate`:
```shell
(dev3) 130 mih@smaug ...asets-meta7-1/datalad/crawl/openneuro (git)-[master] % datalad --dbg rev-aggregate-metadata --force=extraction ds000001
Metadata aggregation:   0%|                                                                                         | 0.00/1.00 [00:00<?, ? datasets/s]Traceback (most recent call last):                                                                                                                     
  File "/home/mih/yoh-mih/datalad-revolution/venvs/dev3/bin/datalad", line 8, in <module>                                                              
    main()
  File "/home/mih/yoh-mih/datalad/datalad/cmdline/main.py", line 500, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/yoh-mih/datalad/datalad/interface/base.py", line 645, in call_from_parser
    ret = list(ret)
  File "/home/mih/yoh-mih/datalad/datalad/interface/utils.py", line 427, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/mih/yoh-mih/datalad/datalad/interface/utils.py", line 520, in _process_results
    for res in results:
  File "/home/mih/yoh-mih/datalad-revolution/datalad_revolution/metadata/revaggregate.py", line 341, in __call__
    ds, extract_from_ds, force, vanished_datasets, cache):
  File "/home/mih/yoh-mih/datalad-revolution/datalad_revolution/metadata/revaggregate.py", line 597, in _do_top_aggregation
    for res in _extract_metadata(aggsrc, ds, exinfo):
  File "/home/mih/yoh-mih/datalad-revolution/datalad_revolution/metadata/revaggregate.py", line 949, in _extract_metadata
    _update_unique_cm(unique_cm, fmeta, exinfo)
  File "/home/mih/yoh-mih/datalad-revolution/datalad_revolution/metadata/revaggregate.py", line 1099, in _update_unique_cm
    msrc_info = exinfo[msrc_key]
KeyError: 'bids'

> /home/mih/yoh-mih/datalad-revolution/datalad_revolution/metadata/revaggregate.py(1099)_update_unique_cm()
-> msrc_info = exinfo[msrc_key]
(Pdb) p exinfo.keys()
dict_keys(['annex', 'datalad_core'])
```

**Comment by mih** [comment]
I have it isolated in a test. A recent "improvement" introduced the breakage.
