### ISSUE TITLE
test fails on my laptop (Python 2.7, virtualenv)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-revolution#59]
```
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=7.20181121+git58-gbc4aa3f0e-1~ndall+1 cmd:git=2.19.2 cmd:system-git=2.20.0.rc2.403.gdbc3b29805 cmd:system-ssh=7.6p1 exifread=2.1.2 git=2.1.11 gitdb=2.0.3 humanize=0.5.1 iso8601=0.1.11 keyring=10.6.0 keyrings.alt=3.0 msgpack=0.5.6 mutagen=1.38 requests=2.18.4 scrapy=1.5.0 six=1.11.0 tqdm=4.19.5 wrapt=1.9.0
Obscure filename: str= "';a&b&cΔЙקم๗あ `|  repr=u' "\';a&b&c\u0394\u0419\u05e7\u0645\u0e57\u3042 `| '
Encodings: default='ascii' filesystem='UTF-8' locale.prefered='UTF-8'
Environment: GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git' LANG='en_US.utf8' GIT_PAGER='less --no-init --quit-if-one-screen' PATH='/home/yoh/proj/datalad/datalad-revolution/venvs/dev/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/sbin:/usr/sbin:/usr/local/sbin'

======================================================================
ERROR: datalad_revolution.tests.test_run.test_inputs_quotes_needed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 1262, in newfunc
    func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 412, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/tests/test_run.py", line 535, in test_inputs_quotes_needed
    ds.rev_save(".")
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/dataset.py", line 147, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 467, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 509, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/revsave.py", line 190, in __call__
    result_renderer='disabled'):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 467, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 509, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/revstatus.py", line 324, in __call__
    content_info_cache):
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/revstatus.py", line 76, in _yield_status
    _cache=cache)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/gitrepo.py", line 327, in diffstatus
    paths=paths, ref=None, untracked=untracked)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/gitrepo.py", line 182, in get_content_info
    path = ut.PurePosixPath(line)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 585, in __new__
    return cls._from_parts(args)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 613, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 606, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 75, in parse_parts
    parts = _py2_fsencode(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 58, in _py2_fsencode
    else part for part in parts]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-14: ordinal not in range(128)

======================================================================
ERROR: datalad_revolution.tests.test_save.test_add_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 412, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/tests/test_save.py", line 336, in test_add_files
    result = ds.rev_save(arg[0], to_git=arg[1])
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/dataset.py", line 147, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 467, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 509, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/revsave.py", line 257, in __call__
    _status=pds_status):
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/gitrepo.py", line 619, in save_
    untracked='all'))
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/gitrepo.py", line 182, in get_content_info
    path = ut.PurePosixPath(line)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 585, in __new__
    return cls._from_parts(args)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 613, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 606, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 75, in parse_parts
    parts = _py2_fsencode(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 58, in _py2_fsencode
    else part for part in parts]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-14: ordinal not in range(128)

======================================================================
ERROR: datalad_revolution.tests.test_save.test_add_subdataset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 412, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 585, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/tests/test_save.py", line 352, in test_add_subdataset
    ok_(subds.repo.dirty)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/gitrepo.py", line 723, in dirty
    untracked='normal', ignore_submodules='other'))
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/gitrepo.py", line 265, in status
    ignore_submodules=ignore_submodules)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/gitrepo.py", line 327, in diffstatus
    paths=paths, ref=None, untracked=untracked)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/gitrepo.py", line 182, in get_content_info
    path = ut.PurePosixPath(line)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 585, in __new__
    return cls._from_parts(args)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 613, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 606, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 75, in parse_parts
    parts = _py2_fsencode(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 58, in _py2_fsencode
    else part for part in parts]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-14: ordinal not in range(128)

======================================================================
ERROR: datalad_revolution.tests.test_save.test_relpath_add
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 412, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/tests/test_save.py", line 513, in test_relpath_add
    eq_(save('testindir')[0]['path'],
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 467, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 509, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/revsave.py", line 257, in __call__
    _status=pds_status):
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/gitrepo.py", line 619, in save_
    untracked='all'))
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/gitrepo.py", line 182, in get_content_info
    path = ut.PurePosixPath(line)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 585, in __new__
    return cls._from_parts(args)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 613, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 606, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 75, in parse_parts
    parts = _py2_fsencode(parts)
  File "/usr/lib/python2.7/dist-packages/pathlib.py", line 58, in _py2_fsencode
    else part for part in parts]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-14: ordinal not in range(128)

======================================================================
ERROR: datalad_revolution.tests.test_save.test_partial_unlocked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 585, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/tests/test_save.py", line 558, in test_partial_unlocked
    (ds.pathobj / 'normal.txt').write_text(u'123')
AttributeError: 'PosixPath' object has no attribute 'write_text'

======================================================================
ERROR: datalad_revolution.tests.test_status.test_status
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 585, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 585, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/tests/test_status.py", line 107, in test_status
    ds = get_deeply_nested_structure(str(_path))
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/tests/utils.py", line 265, in get_deeply_nested_structure
    (ds.pathobj / 'subdir' / 'annexed_file.txt').write_text(u'dummy')
AttributeError: 'PosixPath' object has no attribute 'write_text'

======================================================================
ERROR: datalad_revolution.tests.test_status.test_status_nods
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 585, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 585, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/tests/test_status.py", line 92, in test_status_nods
    ds.rev_status(path=otherpath, on_failure='ignore'),
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/dataset.py", line 147, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 467, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 509, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/revstatus.py", line 290, in __call__
    qds_inrefds = path_under_dataset(ds, qdspath)
  File "/home/yoh/proj/datalad/datalad-revolution/datalad_revolution/dataset.py", line 227, in path_under_dataset
    while root is not None and not ds_path.samefile(root):
AttributeError: 'PosixPath' object has no attribute 'samefile'
```

<details>
<summary>WTF</summary>

```yaml
# WTF
- path: /home/yoh/proj/datalad/datalad-revolution
- logger: <logging.Logger object at 0x7f8c61c1f5d0>
- type: dataset
## configuration <SENSITIVE, report disabled by configuration>
## datalad 
  - full_version: 0.11.1.dev77-ga2ed
  - version: 0.11.1.dev77
## dataset 
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/yoh/proj/datalad/datalad-revolution
  - repo: GitRepo
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.44.0
  - cmd:annex: 7.20181121+git58-gbc4aa3f0e-1~ndall+1
  - cmd:git: 2.19.2
  - cmd:system-git: 2.20.0.rc2.403.gdbc3b29805
  - cmd:system-ssh: 7.6p1
  - exifread: 2.1.2
  - git: 2.1.11
  - gitdb: 2.0.3
  - humanize: 0.5.1
  - iso8601: 0.1.11
  - keyring: 10.6.0
  - keyrings.alt: 3.0
  - msgpack: 0.5.6
  - mutagen: 1.38
  - requests: 2.18.4
  - scrapy: 1.5.0
  - six: 1.11.0
  - tqdm: 4.19.5
  - wrapt: 1.9.0
## environment 
  - GIT_PAGER: less --no-init --quit-if-one-screen
  - GIT_PYTHON_GIT_EXECUTABLE: /usr/lib/git-annex.linux/git
  - LANG: en_US.utf8
  - PATH: /home/yoh/proj/datalad/datalad-revolution/venvs/dev/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/sbin:/usr/sbin:/usr/local/sbin
## extentions 
  - revolution: 
    - description: DataLad revolutionary command suite
    - entrypoints: 
      - datalad_revolution.revcreate.RevCreate: 
        - class: RevCreate
        - load_error: None
        - module: datalad_revolution.revcreate
        - names: 
          - rev-create
          - rev_create
      - datalad_revolution.revrun.RevRun: 
        - class: RevRun
        - load_error: None
        - module: datalad_revolution.revrun
        - names: 
          - rev-run
          - rev_run
      - datalad_revolution.revsave.RevSave: 
        - class: RevSave
        - load_error: None
        - module: datalad_revolution.revsave
        - names: 
          - rev-save
          - rev_save
      - datalad_revolution.revstatus.RevStatus: 
        - class: RevStatus
        - load_error: None
        - module: datalad_revolution.revstatus
        - names: 
          - rev-status
          - rev_status
    - load_error: None
    - module: datalad_revolution
    - version: 0.5.0
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3(multipartupload)(storageclasses)
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.3
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - hook
    - external
  - supported repository versions: 
    - 5
    - 7
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20181121+git58-gbc4aa3f0e-1~ndall+1
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: None
    - module: datalad.metadata.extractors.xmp
    - version: None
## system 
  - distribution: debian/buster/sid
  - encoding: 
    - default: ascii
    - filesystem: UTF-8
    - locale.prefered: UTF-8
  - max_path_length: 297
  - name: Linux
  - release: 4.17.0-1-amd64
  - type: posix
  - version: #1 SMP Debian 4.17.8-1 (2018-07-20)
```

```shell
$> welp pathlib2
PATH       : /usr/lib/python2.7/dist-packages/pathlib2/__init__.pyc
SRC PATH   : /usr/lib/python2.7/dist-packages/pathlib2/__init__.py
VERSION    : 2.3.2
__version__: No __version__
PACKAGE    : python-pathlib2
ii  python-pathlib2 2.3.2-1      all          Backport of the "pathlib" stdlib module (Python 2)
python-pathlib2:
  Installed: 2.3.2-1
  Candidate: 2.3.3-1
  Version table:
     2.3.3-1 600
        600 http://http.debian.net/debian sid/main amd64 Packages
        600 http://http.debian.net/debian sid/main i386 Packages
 *** 2.3.2-1 100
        100 /var/lib/dpkg/status
     2.2.0+really2.1.0-1 100
        100 http://http.debian.net/debian stretch/main amd64 Packages
        100 http://http.debian.net/debian stretch/main i386 Packages
```
</details>

**Comment by bpoldrack** [comment]
> File "/usr/lib/python2.7/dist-packages/pathlib.py", line 58, in _py2_fsencode

vs 

> $> welp pathlib2
PATH       : /usr/lib/python2.7/dist-packages/pathlib2/__init__.pyc
SRC PATH   : /usr/lib/python2.7/dist-packages/pathlib2/__init__.py

Seems your venv is using the wrong pathlib.

**Comment by yarikoptic** [comment]
I am nobody just doing `pip install`. I have both actually - pathlib2 and pathlib, so revolution gets what it asks:
```
datalad/revolution/utils.py-
datalad/revolution/utils.py:# handle this dance once, and import pathlib from here
datalad/revolution/utils.py-# in all other places
datalad/revolution/utils.py-try:
datalad/revolution/utils.py:    from pathlib import (
datalad/revolution/utils.py-        Path,
datalad/revolution/utils.py-        PurePosixPath,
datalad/revolution/utils.py-    )
datalad/revolution/utils.py-except ImportError:
datalad/revolution/utils.py:    from pathlib2 import (
datalad/revolution/utils.py-        Path,
datalad/revolution/utils.py-        PurePosixPath,
--
setup.py-        'six>=1.8.0',
setup.py-        'wrapt',
setup.py:        'pathlib2; python_version < "3.0"',  # brought to you by revolution1
setup.py-    ] +
setup.py-    pbar_requires +
(dev) 1 19001 [1].....................................:Fri 07 Dec 2018 02:34:36 PM EST:.
(git)hopa:~datalad/datalad-master[rf-revolution1]git
$> welp pathlib
PATH       : /usr/lib/python2.7/dist-packages/pathlib.pyc
SRC PATH   : /usr/lib/python2.7/dist-packages/pathlib.py
VERSION    : 1.0.1
__version__: No __version__
PACKAGE    : python-pathlib
ii  python-pathlib 1.0.1-2      all          set of Python 2 classes to handle filesystem paths
python-pathlib:
  Installed: 1.0.1-2
  Candidate: 1.0.1-2.1
  Version table:
     1.0.1-2.1 600
        600 http://http.debian.net/debian sid/main amd64 Packages
        600 http://http.debian.net/debian sid/main i386 Packages
 *** 1.0.1-2 100
        100 http://http.debian.net/debian stretch/main amd64 Packages
        100 http://http.debian.net/debian stretch/main i386 Packages
        100 /var/lib/dpkg/status
```

if my pathlib is too old, should somehow be reflected in the code somehow to not use it

**Comment by bpoldrack** [comment]
Hm. Seems to me that `from pathlib` works even though `setup.py:        'pathlib2; python_version < "3.0"',` suggests, that it shouldn't. I guess, this `try ... except` for the import needs to be fixed to explicitly check python version. Or did I misread the intention, @mih ?

**Comment by mih** [comment]
I guess that should do it.
