### ISSUE TITLE
failing tests for the case with spaces in symlinked TMPDIR name

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-revolution#63]
seems revolution has some issues dealing with spaces https://travis-ci.org/datalad/datalad/jobs/465775759

<details>
<summary>failing tests</summary>

```
======================================================================
FAIL: datalad.revolution.tests.test_save.test_add_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 431, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/revolution/tests/test_save.py", line 338, in test_add_files
    assert_result_count(result, 1, path=str(ds.pathobj / a))
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 1225, in assert_result_count
    dumps(results, indent=1, default=lambda x: str(x))))
AssertionError: Got 0 instead of 1 expected results matching {'path': '/var/tmp/sym link/datalad_temp_tree_test_add_filesm50v6p75/test_annex.txt'}. Inspected 2 record(s):
[
 {
  "type": "file",
  "action": "add",
  "path": "/tmp/datalad_temp_tree_test_add_filesm50v6p75/test_annex.txt",
  "key": "MD5E-s10--3fde983384d59dd67f3ccba74e2bea6c.txt",
  "status": "ok",
  "refds": "/tmp/datalad_temp_tree_test_add_filesm50v6p75"
 },
 {
  "type": "dataset",
  "action": "save",
  "path": "/var/tmp/sym link/datalad_temp_tree_test_add_filesm50v6p75",
  "status": "ok",
  "refds": "/var/tmp/sym link/datalad_temp_tree_test_add_filesm50v6p75"
 }
]
-------------------- >> begin captured logging << --------------------
datalad.revolution.create: INFO   : RSS/VMS: 103004/434224 kB ...>revcreate:305  Creating a new annex repo at /var/tmp/sym link/datalad_temp_tree_test_add_filesm50v6p75
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: datalad.revolution.tests.test_save.test_add_mimetypes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 431, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/revolution/tests/test_save.py", line 408, in test_add_mimetypes
    assert_in(p, annexinfo)
AssertionError: PosixPath('/var/tmp/sym link/datalad_temp_tree_test_add_mimetypesyuboit1f/empty') not found in OrderedDict([(PosixPath('/tmp/datalad_temp_tree_test_add_mimetypesyuboit1f/.datalad/.gitattributes'), {'type': 'file', 'gitshasum': 'ccd8569732fe7ae639d9d0d0769f9db9a52f6328'}), (PosixPath('/tmp/datalad_temp_tree_test_add_mimetypesyuboit1f/.datalad/config'), {'type': 'file', 'gitshasum': '114b87e50b76eb0b96f3c39637a6fc1871b62ede'}), (PosixPath('/tmp/datalad_temp_tree_test_add_mimetypesyuboit1f/.gitattributes'), {'type': 'file', 'gitshasum': '13bf395482c4666d23ebee93f3d560c837f1adc0'}), (PosixPath('/tmp/datalad_temp_tree_test_add_mimetypesyuboit1f/empty'), {'type': 'file', 'backend': 'MD5E', 'hashdirmixed': '2W/kW/', 'bytesize': '0', 'keyname': 'd41d8cd98f00b204e9800998ecf8427e', 'key': 'MD5E-s0--d41d8cd98f00b204e9800998ecf8427e', 'mtime': 'unknown', 'hashdirlower': 'bcc/8bb/', 'humansize': '0 B', 'gitshasum': 'ce380320e1ddbc7ecc482fa5f49e6e2bccb6eec6'}), (PosixPath('/tmp/datalad_temp_tree_test_add_mimetypesyuboit1f/file.txt'), {'type': 'file', 'gitshasum': 'b649a9bf89116c581f8329b8ec3c79a86a70be04'}), (PosixPath('/tmp/datalad_temp_tree_test_add_mimetypesyuboit1f/file2.txt'), {'type': 'file', 'backend': 'MD5E', 'hashdirmixed': '6K/Pp/', 'bytesize': '24', 'keyname': 'bf86f7535f64fa72c86d398495a9638f.txt', 'key': 'MD5E-s24--bf86f7535f64fa72c86d398495a9638f.txt', 'mtime': 'unknown', 'hashdirlower': 'b93/9f9/', 'humansize': '24 B', 'gitshasum': 'cbc434d81a38cda5589b8910a811e036028fcddf'})])
-------------------- >> begin captured logging << --------------------
datalad.revolution.create: INFO   : RSS/VMS: 103004/434224 kB ...>revcreate:305  Creating a new annex repo at /var/tmp/sym link/datalad_temp_tree_test_add_mimetypesyuboit1f
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: datalad.revolution.tests.test_save.test_relpath_add
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 431, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/revolution/tests/test_save.py", line 514, in test_relpath_add
    op.join(ds.path, 'dir', 'testindir'))
AssertionError: '/tmp/datalad_temp_tree_test_relpath_addqkg3975x/dir/testindir' != '/var/tmp/sym link/datalad_temp_tree_test_relpath_addqkg3975x/dir/testindir'
-------------------- >> begin captured logging << --------------------
datalad.revolution.create: INFO   : RSS/VMS: 103048/434480 kB ...>revcreate:305  Creating a new annex repo at /var/tmp/sym link/datalad_temp_tree_test_relpath_addqkg3975x
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: datalad.revolution.tests.test_save.test_save
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 780, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/revolution/tests/test_save.py", line 117, in test_save
    assert_repo_status(path, annex=isinstance(ds.repo, AnnexRepo))
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/revolution/tests/utils.py", line 100, in assert_repo_status
    % (state, state_files, oktobefound))
AssertionError: unexpected content of state "modified": [PosixPath('/tmp/datalad_temp_clone_url_0e6a0a6y/subds')] != []
-------------------- >> begin captured logging << --------------------
datalad.revolution.create: INFO   : RSS/VMS: 103112/434480 kB ...>revcreate:305  Creating a new annex repo at /var/tmp/sym link/datalad_temp_clone_url_0e6a0a6y/subds
datalad.revolution.create: INFO   : RSS/VMS: 103136/434480 kB ...>revcreate:305  Creating a new annex repo at /var/tmp/sym link/datalad_temp_clone_url_0e6a0a6y/subds/someotherds
--------------------- >> end captured logging << ---------------------
```
</details>

**Comment by mih** [comment]
FTR: Issues discovered so far are issues of symlinks, not spaces
