### ISSUE TITLE
RevolutionDataset.is_installed() false positive

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad-revolution#79]
As I was playing around with using RevolutionDataset throughout core, I noticed that test_install.py:test_implicit_install was failing (output below fold).  is_installed() is reporting that uninstalled datasets are installed, and that looks to be caused by RevolutionDataset's override of the repo attribute.

Here's a script that shows the issue using the revolution extension and DataLad's master:

```python
import os
import tempfile

from datalad.api import rev_create

tmp = tempfile.mkdtemp(suffix="-dlrev-test")
ds = rev_create(tmp)
subds = ds.rev_create("subds")

print(type(subds))


def info():
    print(ds.path, os.listdir(ds.path))
    print(subds.path, os.listdir(subds.path))
    print("installed?", subds.is_installed())
    print("repo", subds.repo)


print("## Installed")
info()
subds.uninstall()
print("## After uninstall")
info()
```

```
[INFO] Creating a new annex repo at /tmp/tmpt2z73j18-dlrev-test 
[INFO] Creating a new annex repo at /tmp/tmpt2z73j18-dlrev-test/subds 
<class 'datalad_revolution.dataset.RevolutionDataset'>
## Installed
/tmp/tmpt2z73j18-dlrev-test ['subds', '.datalad', '.gitmodules', '.git', '.gitattributes']
/tmp/tmpt2z73j18-dlrev-test/subds ['.datalad', '.git', '.gitattributes']
installed? True
repo <AnnexRepo path=/tmp/tmpt2z73j18-dlrev-test/subds (<class 'datalad_revolution.annexrepo.RevolutionAnnexRepo'>)>
## After uninstall
/tmp/tmpt2z73j18-dlrev-test ['subds', '.datalad', '.gitmodules', '.git', '.gitattributes']
/tmp/tmpt2z73j18-dlrev-test/subds []
installed? True
repo <AnnexRepo path=/tmp/tmpt2z73j18-dlrev-test/subds (<class 'datalad_revolution.annexrepo.RevolutionAnnexRepo'>)>
```

<details>
<summary>core test failure</summary>

```
======================================================================
FAIL: datalad.distribution.tests.test_install.test_implicit_install
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyle/src/python/venvs/dl-rev-merge/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/kyle/src/python/datalad-revmerge/datalad/tests/utils.py", line 605, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/kyle/src/python/datalad-revmerge/datalad/tests/utils.py", line 605, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/kyle/src/python/datalad-revmerge/datalad/distribution/tests/test_install.py", line 577, in test_implicit_install
    ok_(not sub.is_installed())
AssertionError: None
```

</details>

**Comment by mih** [comment]
Hmm, indeed. TBH I am a bit surprised by the size of the diff:

```diff
--- core        2019-02-04 20:37:13.892396672 +0100
+++ rev 2019-02-04 20:35:49.126408126 +0100
@@ -1,82 +1,39 @@
     @property
     def repo(self):
         """Get an instance of the version control system/repo for this dataset,
-        or None if there is none yet (or none anymore).
+        or None if there is none yet.
 
-        If testing the validity of an instance of GitRepo is guaranteed to be
-        really cheap this could also serve as a test whether a repo is present.
-
-        Note, that this property is evaluated every time it is used. If used
-        multiple times within a function it's probably a good idea to store its
-        value in a local variable and use this variable instead.
+        If creating an instance of GitRepo is guaranteed to be really cheap
+        this could also serve as a test whether a repo is present.
 
         Returns
         -------
-        GitRepo or AnnexRepo
+        GitRepo
         """
 
-        # If we already got a *Repo instance, check whether it's still valid;
-        # Note, that this basically does part of the testing that would
-        # (implicitly) be done in the loop below again. So, there's still
-        # potential to speed up when we actually need to get a new instance
-        # (or none). But it's still faster for the vast majority of cases.
-        #
-        # TODO: Dig deeper into it and melt with new instance guessing. This
-        # should also involve to reduce redundancy of testing such things from
-        # within Flyweight.__call__, AnnexRepo.__init__ and GitRepo.__init__!
-        #
-        # Also note, that this could be forged into a single big condition, but
-        # that is hard to read and we should be well aware of the actual
-        # criteria here:
-        if self._repo is not None and realpath(self.path) == self._repo.path:
-            # we got a repo and path references still match
-            if isinstance(self._repo, AnnexRepo):
-                # it's supposed to be an annex
-                if self._repo is AnnexRepo._unique_instances.get(
-                        self._repo.path, None) and \
-                        AnnexRepo.is_valid_repo(self._repo.path,
-                                                allow_noninitialized=True):
-                    # it's still the object registered as flyweight and it's a
-                    # valid annex repo
-                    return self._repo
-            elif isinstance(self._repo, GitRepo):
-                # it's supposed to be a plain git
-                if self._repo is GitRepo._unique_instances.get(
-                        self._repo.path, None) and \
-                        GitRepo.is_valid_repo(self._repo.path) and not \
-                        self._repo.is_with_annex():
-                    # it's still the object registered as flyweight, it's a
-                    # valid git repo and it hasn't turned into an annex
-                    return self._repo
+        # Note: lazy loading was disabled, since this is provided by the
+        # flyweight pattern already and a possible invalidation of an existing
+        # instance has to be done therein.
+        # TODO: Still this is somewhat problematic. We can't invalidate strong
+        # references
 
-        # Note: Although it looks like the "self._repo = None" assignments
-        # could be used instead of variable "valid", that's a big difference!
-        # The *Repo instances are flyweights, not singletons. self._repo might
-        # be the last reference, which would lead to those objects being
-        # destroyed and therefore the constructor call would result in an
-        # actually new instance. This is unnecessarily costly.
-        valid = False
         for cls, ckw, kw in (
                 # TODO: Do we really want to allow_noninitialized=True here?
                 # And if so, leave a proper comment!
-                (AnnexRepo, {'allow_noninitialized': True}, {'init': False}),
-                (GitRepo, {}, {})
+                (RevolutionAnnexRepo, {'allow_noninitialized': True}, {'init': False}),
+                (RevolutionGitRepo, {}, {})
         ):
             if cls.is_valid_repo(self._path, **ckw):
                 try:
                     lgr.log(5, "Detected %s at %s", cls, self._path)
                     self._repo = cls(self._path, create=False, **kw)
-                    valid = True
                     break
-                except (InvalidGitRepositoryError, NoSuchPathError,
-                        InvalidAnnexRepositoryError) as exc:
+                except (InvalidGitRepositoryError, NoSuchPathError) as exc:
                     lgr.log(5,
                             "Oops -- guess on repo type was wrong?: %s",
                             exc_str(exc))
-
-        if not valid:
-            self._repo = None
-
+                    pass
+                # version problems come as RuntimeError: DO NOT CATCH!
         if self._repo is None:
             # Often .repo is requested to 'sense' if anything is installed
             # under, and if so -- to proceed forward. Thus log here only
```

**Comment by mih** [comment]
@bpoldrack Can you please have a look what of this diff needs to change to make it behave sensibly again? Thx.

**Comment by bpoldrack** [comment]
FTR:

Tried to avoid the code duplication in a first approach in #82, by simply wrapping `Dataset.repo` and change the type of the return value. This doesn't work. Because we are dealing with flyweights. Those are not really singletons. Instead they'll be destroyed if there's no reference anymore. Which leads to the necessity to store a reference somewhere, because otherwise you get a new instance everytime. this isn't only costly, it leads to things being associated with objects that aren't there anymore. Failing tests in #82 showed that for a patched bound method of `config`, which itself relies on `repo` (the wrong not anymore existing one). 

Conclusion: `RevolutionDataset` needs to hold a reference to its `Revolution*Repo`. But if it does, it also needs to evaluate it (still valid?). This is exactly what all the code I wanted to avoid to double maintain is about. So - there's no way around, we need the duplication. Will do.
